project_name: 'BarcodeDetection'
exp_name: 'exp_1'


yolo_config:
  path: 'yolov8n.pt'
  dataset_path: 'data/dataset.yaml'
  epochs_num: 30

  img_size: 640
  batch_size: 32
  cache: True
  device: 0
  workers: 2
  optimizer: 'auto'
  close_mosaic: 0
  amp: True
  lr0: 0.01
  lrf: 0.01
  momentum: 0.937
  weight_decay: 0.0005
  warmup_epochs: 3
  warmup_momentum: 0.8
  warmup_bias_lr: 0.1
